USE [SSDI]
GO

/****** Object:  Table [dbo].[RECORDS]    Script Date: 04/02/2014 13:36:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[RECORDS](
	[SSAN] [int] NOT NULL,
	[LASTNAME] [varchar](50) NOT NULL,
	[FIRSTNAME] [varchar](50) NOT NULL,
	[MIDDLENAME] [varchar](50) NOT NULL,
	[BIRTHBEGIN] [datetime2](7) NOT NULL,
	[BIRTHEND] [datetime2](7) NOT NULL,
	[DEATHBEGIN] [datetime2](7) NOT NULL,
	[DEATHEND] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_RECORDS] PRIMARY KEY CLUSTERED 
(
	[SSAN] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

